### ISSUE TITLE
I report a error about set-logic BV

### ISSUE THREAD

**Issue by H0TSUN** [purdue-cap/DryadSynth#1]
Hello, I am Synthesis beginner.
I want to test your great project. But I encounter unknown error during synthesis set-logic BV. 
Only benchmarks related to (set-logic BV) get the error below.
 My console print out "java.lang.NullPointerException"

I also upload my error figure.
I am so sorry. Thank you.

![1F97146B-403D-41DA-BE56-0B2482963287](https://user-images.githubusercontent.com/38975081/93711194-467d6080-fb87-11ea-8423-8bfc3213454c.png)

**Comment by xkqiu** [comment]
Glad to hear from you! 

The current version supports the `LIA` logic only. In other words, it supports all SyGuS problems under the `CLIA` and `INV` categories, as well as problems under the `General` category with `(set logic LIA)`. That said, we plan to extend DryadSynth with preliminary support of `BV` in the next few months. Stay tuned!

**Comment by H0TSUN** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
